
project_id = "vsxbpknreazkcvjswycc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54324
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

# Edge functions configuration
[functions."v2-estimate-intent"]
verify_jwt = true

[functions."generate-estimate-content"]
verify_jwt = true

[functions."extract-information"]
verify_jwt = true

[functions."transcribe-audio"]
verify_jwt = true

[functions."generate_proposal"]
verify_jwt = true
