
import { z } from "https://deno.land/x/zod@v3.16.1/mod.ts";

// Updated schemas to match the actual AI-generated structure from the prompt template
export const ColorApprovalSchema = z.object({
  colorCode: z.string(),
  colorName: z.string(),
  surfaces: z.string(),
  approved: z.boolean().default(false)
});

export const OptionalUpgradeSchema = z.object({
  selected: z.boolean().default(false),
  description: z.string(),
  quantity: z.number(),
  unitPrice: z.number(),
  lineTotal: z.number()
});

// Updated to match the actual structure being generated by the AI
export const PDFContentSchema = z.object({
  projectOverview: z.string(),
  scopeOfWork: z.string(),
  materialsAndLabor: z.string(),
  timeline: z.string(),
  termsAndConditions: z.string(),
  additionalNotes: z.string()
});

export type PDFContent = z.infer<typeof PDFContentSchema>;
export type ColorApproval = z.infer<typeof ColorApprovalSchema>;
export type OptionalUpgrade = z.infer<typeof OptionalUpgradeSchema>;
