
import React, { useEffect, useState } from 'react';
import { formatProposalText } from '@/utils/formatProposalText';
import { Printer } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import CoverPage from './CoverPage';

// Add print-specific styles
const printStyles = `
  @page {
    margin: 0.75in;
    size: 8.5in 11in;
  }
`;

interface PrintableProposalProps {
  proposal: string;
  metadata: {
    clientName?: string;
    clientPhone?: string; // Added
    clientEmail?: string; // Added
    clientAddress?: string; // Added
    preparedBy?: string; // Added
    jobType?: string;
    status?: string;
  };
  companyProfile?: {
    business_name?: string; // Renamed from companyName
    location?: string; // Renamed from companyAddress
    services_offered?: string; // Renamed from companyServices
    logo_url?: string;
    email?: string;
    phone?: string;
    owner_name?: string; // Added (used by CoverPage)
    // Removed warranty as it's not used in CoverPage
  };
}

const PrintableProposal: React.FC<PrintableProposalProps> = ({
  proposal,
  metadata,
  companyProfile,
}) => {
  const [coverImageUrl, setCoverImageUrl] = useState<string | null>(null);

  useEffect(() => {
    if (window.opener) {
      window.print();
    }
  }, []);

  useEffect(() => {
    const fetchCoverImage = async () => {
      const { data } = await supabase
        .from('proposal_pdf_settings')
        .select('cover_image_url')
        .single();
      
      setCoverImageUrl(data?.cover_image_url || null);
    };

    fetchCoverImage();
  }, []);

  return (
    <div className="min-h-screen bg-white font-sans">
      {/* Inject print styles */}
      <style dangerouslySetInnerHTML={{ __html: printStyles }} />
      
      <div className="p-4 mb-6 bg-blue-50 rounded-lg print:hidden">
        <h2 className="text-lg font-semibold flex items-center gap-2">
          <Printer className="h-5 w-5" />
          Print Instructions
        </h2>
        <p className="mt-2 text-sm text-gray-600">
          To save as PDF:
          <br />
          • Desktop: Select "Save as PDF" in the print dialog
          <br />
          • iOS: Tap the share icon and select "Print" or "Save as PDF"
          <br />
          • Android: Select "Save as PDF" in the print options
        </p>
      </div>

      <div className="max-w-[750px] mx-auto px-8 print:max-w-none print:w-full print:mx-0">
        
        {/* Cover Page */}
        <div className="print:page-break-after">
          <CoverPage 
            metadata={metadata}
            companyProfile={companyProfile}
            coverImageUrl={coverImageUrl}
          />
        </div>

        <div className="prose max-w-none print:prose-sm leading-relaxed mt-8 print:mt-4">
          {formatProposalText(proposal)}
        </div>

        <footer className="mt-12 pt-6 border-t border-gray-200 text-sm text-gray-600 print:mt-8">
          <p>Generated by {companyProfile?.business_name || "Company"}</p>
          <p className="mt-1">© {new Date().getFullYear()} All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
};

export default PrintableProposal;