
import React, { useEffect } from 'react';
import { formatProposalText } from '@/utils/formatProposalText';
import { Printer } from 'lucide-react';

interface PrintableProposalProps {
  proposal: string;
  metadata: {
    clientName?: string;
    jobType?: string;
    status?: string;
  };
  companyProfile?: {
    companyName?: string;
    companyAddress?: string;
    companyServices?: string;
  };
}

const PrintableProposal: React.FC<PrintableProposalProps> = ({
  proposal,
  metadata,
  companyProfile,
}) => {
  useEffect(() => {
    // If opened in a new window, trigger print automatically
    if (window.opener) {
      window.print();
    }
  }, []);

  return (
    <div className="min-h-screen bg-white">
      {/* Print Instructions - Hidden in Print */}
      <div className="p-4 mb-6 bg-blue-50 rounded-lg print:hidden">
        <h2 className="text-lg font-semibold flex items-center gap-2">
          <Printer className="h-5 w-5" />
          Print Instructions
        </h2>
        <p className="mt-2 text-sm text-gray-600">
          To save as PDF:
          <br />
          • Desktop: Select "Save as PDF" in the print dialog
          <br />
          • iOS: Tap the share icon and select "Print" or "Save as PDF"
          <br />
          • Android: Select "Save as PDF" in the print options
        </p>
      </div>

      {/* Proposal Content - Optimized for Print */}
      <div className="max-w-[800px] mx-auto p-8 print:p-6">
        {/* Header */}
        <div className="mb-8 print:mb-6">
          {companyProfile?.companyName && (
            <h1 className="text-2xl font-bold text-gray-900 mb-2">
              {companyProfile.companyName}
            </h1>
          )}
          {companyProfile?.companyAddress && (
            <p className="text-gray-600">{companyProfile.companyAddress}</p>
          )}
        </div>

        {/* Client Info */}
        <div className="mb-8 print:mb-6">
          <h2 className="text-xl font-semibold mb-2">
            Proposal for {metadata.clientName || "Client"}
          </h2>
          {metadata.jobType && (
            <p className="text-gray-600">Project Type: {metadata.jobType}</p>
          )}
          <p className="text-gray-600">Date: {new Date().toLocaleDateString()}</p>
        </div>

        {/* Main Content */}
        <div className="prose max-w-none print:prose-sm">
          {formatProposalText(proposal)}
        </div>

        {/* Footer */}
        <footer className="mt-12 pt-6 border-t border-gray-200 text-sm text-gray-600 print:mt-8">
          <p>Generated by {companyProfile?.companyName || "Company"}</p>
          <p className="mt-1">© {new Date().getFullYear()} All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
};

export default PrintableProposal;
