// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsxbpknreazkcvjswycc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeGJwa25yZWF6a2N2anN3eWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTE0MDUsImV4cCI6MjA1OTI4NzQwNX0.1WU4BfcyDWmyKeqBpH3W1-7zqLMuvKjZfh7E2Jw6Voo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);